name: 'Private Packagist Artifact Publishing'
description: 'GitHub Action to publish artifacts as package versions to Private Packagist'

author: Packagist Conductors GmbH <contact@packagist.com>

inputs:
  package_name:
    description: The name of the package that will be published.
    required: true
  organization_url_name:
    description: The URL name of your Private Packagist organization.
    required: true
  private_packagist_url:
    description: The URL to the Private Packagist installation
    default: 'https://packagist.com'
    required: false
  artifact:
    description: Full path to the artifact file to publish.

runs:
  using: "composite"
  steps:
    - name: Store GITHUB_ACTION_PATH
      shell: "bash"
      run: echo "ACTION_DIR=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV # zizmor: ignore[github-env]

    - name: "Check if PHP is installed"
      shell: "bash"
      run: command -v $(which php) 2>&1 >/dev/null && echo "PHP_INSTALLED=yes" >> $GITHUB_ENV || echo "PHP_INSTALLED=no" >> $GITHUB_ENV

    - name: "Validate PHP version"
      shell: "bash"
      run: "${ACTION_DIR}/bin/php_version_check.sh 7.2.5"
      if: ${{ env.PHP_INSTALLED == 'yes' }}
      env:
        ACTION_DIR: ${{ env.ACTION_DIR }}


    - name: Install PHP
      uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # 2.35.4
      if: ${{ env.PHP_INSTALLED == 'no' }}
      with:
        php-version: "8.4"

    - name: Install dependencies
      uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1
      with:
        working-directory: "${{ env.ACTION_DIR }}" # Cannot use ${GITHUB_ACTION_PATH} here because it resolves to the action dir of ramsey/composer-install

    - name: Publish
      shell: "bash"
      run: 'php ${ACTION_DIR}/bin/publish.php "${INPUTS_PACKAGE_NAME}" "${INPUTS_ARTIFACT}" "${INPUTS_ORGANIZATION_URL_NAME}" "${INPUTS_PRIVATE_PACKAGIST_URL}"'
      env:
        INPUTS_PACKAGE_NAME: ${{ inputs.package_name }}
        INPUTS_ARTIFACT: ${{ inputs.artifact }}
        INPUTS_ORGANIZATION_URL_NAME: ${{ inputs.organization_url_name }}
        INPUTS_PRIVATE_PACKAGIST_URL: ${{ inputs.private_packagist_url }}
